### ISSUE TITLE
Got this for a crash dump help

### ISSUE THREAD

**Issue by xLordShadow** [HotshotHD/PocketMorph#1]
Genisys Crash Dump Sat Apr 9 22:16:39 MDT 2016

Error: Cannot use pocketmine\nbt\tag\Int as Int because 'Int' is a special class name
File: /phar_PocketMorph-master_OvjhWMvmcczHGjp.phar/src/pocketmorph/morph/MorphZombieVillager
Line: 6
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起
BAD PLUGIN : PocketMorph v1.0.0

Code:

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #249 [Protocol 46; API 2.0.0]
uname -a: Linux mc50.vgmc.us 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by HotshotHD** [comment]
Fixed.

**Comment by xLordShadow** [comment]
Thanks will try again

**Comment by xLordShadow** [comment]
Genisys Crash Dump Sat Apr 9 22:23:59 MDT 2016

Error: Cannot use pocketmine\nbt\tag\Int as Int because 'Int' is a special class name
File: /phar_PocketMorph-master_OxbMb3bhTLV3SzU.phar/src/pocketmorph/morph/MorphVillager
Line: 6
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起
BAD PLUGIN : PocketMorph v1.0.0

Code:

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #249 [Protocol 46; API 2.0.0]
uname -a: Linux mc50.vgmc.us 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by xLordShadow** [comment]
May have to change all

**Comment by xLordShadow** [comment]
Genisys Crash Dump Sat Apr 9 22:35:16 MDT 2016

Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name
File: /phar_PocketMorph-master_FvXdATP12qrgTrR.phar/src/pocketmorph/morph/manager/MorphManager
Line: 11
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起
BAD PLUGIN : PocketMorph v1.0.0

Code:

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #249 [Protocol 46; API 2.0.0]
uname -a: Linux mc50.vgmc.us 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by HotshotHD** [comment]
Are you using php5 or php7?

**Comment by xLordShadow** [comment]
Php 7

**Comment by HotshotHD** [comment]
Please use this tool by @PEMapModder to update the plugin: pmt.mcpe.me/api2. Upload the file and click 'inject'

**Comment by xLordShadow** [comment]
Thanks

**Comment by xLordShadow** [comment]
The Zip File won't work, and if I do a phar it tells me API 2.0.0 Is already declared.

**Comment by HotshotHD** [comment]
I removed api 2.0.0 from the api array. It should work when u try to update it now, sorry for the inconvenience :(

**Comment by xLordShadow** [comment]
All good stuff happens
