### ISSUE TITLE
Another Issue

### ISSUE THREAD

**Issue by xLordShadow** [HotshotHD/PocketMorph#8]
Genisys Crash Dump Wed May 25 16:16:58 MDT 2016

Error: Cannot use pocketmine\nbt\tag\Int as Int because 'Int' is a special class name
File: /PocketMorph-master/src/pocketmorph/morph/MorphVillager
Line: 5
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起
BAD PLUGIN : PocketMorph v1.0.0

Code:

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #391 [Protocol 70; API 2.0.0]
uname -a: Linux mc52.vgmc.us 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by HotshotHD** [comment]
Fixed
